### ISSUE TITLE
Ubuntu 16.04, PHP7 and new Java support

### ISSUE THREAD

**Issue by arijuki** [bjornjohansen/minit-yui#1]
Does Minit-YUI support new versions of above mentioned software? Does it matter which Java to install?

**Comment by bjornjohansen** [comment]
I haven’t tested it on PHP7 yet, but I took a quick look at the code and did not see any potential problems there. As for the Java version, I couldn’t find any Java version related issues in the [YUI Compressor](https://github.com/yui/yuicompressor) issue tracker.
